let products=[];let activeCategory='All';let cart=JSON.parse(localStorage.getItem('nova_cart_v4')||'[]');
const $=s=>document.querySelector(s);const money=n=>Number(n||0).toLocaleString('en-PK');const catIcons={All:'✨',Electronics:'🎧',Gaming:'🎮',Shoes:'👟',Tracksuits:'👕',Trousers:'👖',Accessories:'⌚',Other:'📦'};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
async function load(){try{products=await fetch('/api/products').then(r=>r.json());renderCategories();renderFeatured();renderProducts();renderCart()}catch{toast('Could not load products. Make sure the server is running.')}}
function imageOf(p){return p.image||`https://placehold.co/700x700/171717/f6b817?text=${encodeURIComponent(p.name)}`}
function renderCategories(){const cats=['All',...new Set(products.map(p=>p.category))];$('#categoryGrid').innerHTML=cats.filter(x=>x!=='All').map(c=>`<button class="category-card" data-cat="${esc(c)}"><span class="icon">${catIcons[c]||'🛍️'}</span><b>${esc(c)}</b><small>${products.filter(p=>p.category===c).length} products</small><i>Shop now →</i></button>`).join('');$('#filterChips').innerHTML=cats.map(c=>`<button class="chip ${c===activeCategory?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');document.querySelectorAll('[data-cat]').forEach(x=>x.onclick=()=>{activeCategory=x.dataset.cat;renderCategories();renderProducts();location.hash='products'})}
function discount(p){if(!p.compare_price||p.compare_price<=p.price)return 0;return Math.round((1-p.price/p.compare_price)*100)}
function card(p,i=0){const off=discount(p);return `<article class="product-card"><div class="product-image" onclick="openProduct(${p.id})"><img src="${imageOf(p)}" alt="${esc(p.name)}" onerror="this.src='https://placehold.co/700x700/171717/f6b817?text=NOVA+DIGITAL'"><span class="badge">${off?`-${off}%`:(i<3?'HOT':'NOVA')}</span><button class="wish" aria-label="Wishlist">♡</button></div><div class="product-body"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><div class="rating">★★★★★ <span>New</span></div><div class="price-row"><div><span class="price">Rs. ${money(p.price)}</span>${p.compare_price>p.price?`<s>Rs. ${money(p.compare_price)}</s>`:''}</div><span class="stock">${p.stock>0?p.stock+' left':'Out of stock'}</span></div><button class="add-btn" onclick="addToCart(${p.id})" ${p.stock<1?'disabled':''}>${p.stock<1?'Out of Stock':'Add to Cart'}</button></div></article>`}
function renderFeatured(){const list=[...products].sort((a,b)=>b.id-a.id).slice(0,5);$('#featuredGrid').innerHTML=list.map(card).join('')}
function renderProducts(){const q=$('#searchInput').value.trim().toLowerCase();let list=products.filter(p=>(activeCategory==='All'||p.category===activeCategory)&&(!q||`${p.name} ${p.category} ${p.description||''}`.toLowerCase().includes(q)));const sort=$('#sortSelect').value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);if(sort==='new')list.sort((a,b)=>b.id-a.id);$('#productGrid').innerHTML=list.map(card).join('');$('#emptyState').hidden=!!list.length}
function addToCart(id){const p=products.find(x=>x.id===id);if(!p||p.stock<1)return;const x=cart.find(x=>x.product_id===id);if(x){if(x.quantity>=p.stock)return toast('Maximum available stock reached');x.quantity++}else cart.push({product_id:id,quantity:1});saveCart();toast(`${p.name} added to cart`)}
function saveCart(){localStorage.setItem('nova_cart_v4',JSON.stringify(cart));renderCart()}function cartTotals(){let subtotal=0;for(const x of cart){const p=products.find(p=>p.id===x.product_id);if(p)subtotal+=p.price*x.quantity}const delivery=subtotal===0?0:(subtotal>=1500?0:250);return{subtotal,delivery,total:subtotal+delivery}}
function renderCart(){$('#cartCount').textContent=cart.reduce((a,x)=>a+x.quantity,0);$('#cartItems').innerHTML=cart.length?cart.map(x=>{const p=products.find(p=>p.id===x.product_id);if(!p)return'';return `<div class="cart-item"><img src="${imageOf(p)}"><div><h4>${esc(p.name)}</h4><b>Rs. ${money(p.price*x.quantity)}</b><div class="qty"><button onclick="qty(${p.id},-1)">−</button><span>${x.quantity}</span><button onclick="qty(${p.id},1)">+</button></div></div><button class="remove" onclick="removeItem(${p.id})">Remove</button></div>`}).join(''):'<p class="empty">Your cart is empty.</p>';const t=cartTotals();$('#subtotal').textContent=money(t.subtotal);$('#deliveryText').textContent=t.delivery?`Rs. ${money(t.delivery)}`:'FREE';$('#grandTotal').textContent=money(t.total)}
function qty(id,d){const x=cart.find(x=>x.product_id===id),p=products.find(p=>p.id===id);if(!x||!p)return;x.quantity=Math.max(1,Math.min(p.stock,x.quantity+d));saveCart()}function removeItem(id){cart=cart.filter(x=>x.product_id!==id);saveCart()}function openDrawer(){$('#cartDrawer').classList.add('open');$('#overlay').hidden=false}function closeDrawer(){$('#cartDrawer').classList.remove('open');$('#overlay').hidden=true}
function openProduct(id){const p=products.find(x=>x.id===id);if(!p)return;$('#modalImage').src=imageOf(p);$('#modalCategory').textContent=p.category;$('#modalName').textContent=p.name;$('#modalDescription').textContent=p.description||'Quality product from NOVA DIGITAL.';$('#modalPrice').innerHTML=`Rs. ${money(p.price)} ${p.compare_price>p.price?`<s>Rs. ${money(p.compare_price)}</s>`:''}`;$('#modalStock').textContent=p.stock>0?`${p.stock} pieces available`:'Out of stock';$('#modalAdd').disabled=p.stock<1;$('#modalAdd').onclick=()=>{addToCart(p.id);$('#productModal').hidden=true};$('#productModal').hidden=false}function openTrack(){$('#trackModal').hidden=false;$('#trackResult').innerHTML=''}
$('#cartBtn').onclick=openDrawer;$('[data-close]').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;$('#searchInput').oninput=renderProducts;$('#searchBtn').onclick=()=>{renderProducts();location.hash='products'};$('#sortSelect').onchange=renderProducts;$('#trackBtn').onclick=openTrack;$('#heroTrack').onclick=openTrack;$('#footerTrack').onclick=openTrack;$('[data-modal-close]').onclick=()=>$('#productModal').hidden=true;$('[data-track-close]').onclick=()=>$('#trackModal').hidden=true;
$('#checkoutForm').onsubmit=async e=>{e.preventDefault();if(!cart.length)return toast('Cart is empty');const f=new FormData(e.target);const payload={customer_name:f.get('customer_name'),customer_email:f.get('customer_email'),phone:f.get('phone'),province:f.get('province'),city:f.get('city'),address:f.get('address'),notes:f.get('notes'),items:cart};const r=await fetch('/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)return toast(d.error||'Order failed');cart=[];saveCart();e.target.reset();closeDrawer();toast(`Order ND-${d.order_id} placed successfully`);setTimeout(()=>alert(`ORDER CONFIRMED ✅\n\nOrder Number: ND-${d.order_id}\nTotal: Rs. ${money(d.total)}\nDelivery: ${d.delivery_fee?`Rs. ${money(d.delivery_fee)}`:'FREE'}\nPayment: Cash on Delivery\n\nSave your order number for tracking.`),250)};
$('#trackForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const id=f.get('order_id'),phone=f.get('phone');const r=await fetch(`/api/orders/${id}/track?phone=${encodeURIComponent(phone)}`);const d=await r.json();if(!r.ok){$('#trackResult').innerHTML=`<div class="status-box">${esc(d.error||'Order not found')}</div>`;return}$('#trackResult').innerHTML=`<div class="status-box"><b>Order ND-${d.id}</b><p>Status: <span class="status-badge">${esc(d.status)}</span></p><p>Total: Rs. ${money(d.total)}</p>${d.tracking_no?`<p>Courier: ${esc(d.courier)}<br>Tracking: <b>${esc(d.tracking_no)}</b></p>`:''}<p>Placed: ${new Date(d.created_at).toLocaleString()}</p></div>`};
load();
