let token=localStorage.getItem('nova_admin_token_v4')||'';
let lastOrders=[];
const $=s=>document.querySelector(s);const money=n=>Number(n||0).toLocaleString('en-PK');
function toast(m){const t=$('#adminToast');t.textContent=m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2300)}
async function api(url,opt={}){const headers={...(opt.headers||{}),Authorization:`Bearer ${token}`};if(!(opt.body instanceof FormData))headers['Content-Type']='application/json';const r=await fetch(url,{...opt,headers});if(r.status===401&&token){logout();throw new Error('Session expired')}return r}
function setLoggedInView(on){const login=$('#loginView'),dash=$('#dashboard');login.hidden=on;dash.hidden=!on;login.style.display=on?'none':'grid';dash.style.display=on?'grid':'none'}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginMsg').textContent='Checking login...';try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#email').value.trim(),password:$('#password').value})});const d=await r.json();if(!r.ok){$('#loginMsg').textContent=d.error||'Login failed';return}token=d.token;localStorage.setItem('nova_admin_token_v4',token);$('#loginMsg').textContent='Login successful';setLoggedInView(true);await showDashboard()}catch(err){console.error(err);$('#loginMsg').textContent='Dashboard could not load: '+(err.message||'unknown error')}};
function logout(){localStorage.removeItem('nova_admin_token_v4');token='';setLoggedInView(false);$('#loginMsg').textContent=''}$('#logout').onclick=logout;
async function showDashboard(){setLoggedInView(true);const results=await Promise.allSettled([loadStats(),loadProducts(),loadOrders()]);const failed=results.filter(x=>x.status==='rejected');if(failed.length){console.error('Dashboard load errors',failed);toast('Login successful. Some dashboard data could not load.')}else{toast('Welcome to NOVA Seller Center')}}
document.querySelectorAll('.navbtn').forEach(b=>b.onclick=()=>{document.querySelectorAll('.navbtn').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.hidden=true);$(`#${b.dataset.tab}Tab`).hidden=false;$('#pageTitle').textContent=b.textContent.trim().replace(/^[^A-Za-z]+/,'')});
async function loadStats(){const r=await api('/api/admin/stats');const s=await r.json();if(!r.ok)throw new Error(s.error);$('#stats').innerHTML=`<div class="stat"><span>Total Products</span><b>${s.products}</b></div><div class="stat"><span>Total Orders</span><b>${s.orders}</b></div><div class="stat"><span>Open Orders</span><b>${s.pending}</b></div><div class="stat"><span>Delivered Revenue</span><b>Rs. ${money(s.revenue)}</b></div>`}
async function loadProducts(){const p=await fetch('/api/products').then(r=>r.json());$('#productList').innerHTML=`<table class="table"><thead><tr><th>Photo</th><th>Product</th><th>Category</th><th>Price</th><th>Stock</th><th>Action</th></tr></thead><tbody>${p.map(x=>`<tr><td><img class="thumb" src="${x.image||'https://placehold.co/100/1a1a1a/f5b91c?text=ND'}"></td><td><b>${esc(x.name)}</b><br><small>${esc(x.description||'')}</small></td><td>${esc(x.category)}</td><td><b>Rs. ${money(x.price)}</b>${x.compare_price>0?`<br><small><s>Rs. ${money(x.compare_price)}</s></small>`:''}</td><td>${x.stock}</td><td><button class="smallbtn" onclick="editProduct(${x.id})">Edit</button> <button class="smallbtn danger" onclick="deleteProduct(${x.id})">Delete</button></td></tr>`).join('')}</tbody></table>`}
async function loadOrders(){
 const r=await api('/api/admin/orders'),o=await r.json();if(!r.ok)throw new Error(o.error);lastOrders=o;
 const statuses=['Pending','Confirmed','Ready to Ship','Shipped','Delivered','Cancelled'];
 const pendingPays=o.filter(x=>x.payment_method==='Easypaisa'&&x.payment_status==='Payment Pending');
 const alert=$('#paymentAlert');
 if(pendingPays.length){
   alert.hidden=false;
   alert.innerHTML=`<h3>💚 ${pendingPays.length} Easypaisa payment${pendingPays.length>1?'s':''} waiting for verification</h3><p>Open Orders and compare each Transaction ID with your Easypaisa account before marking it Paid.</p>`;
   toast(`${pendingPays.length} Easypaisa payment verification pending`);
 }else{alert.hidden=true}
 const paymentCell=x=>{
   const method=x.payment_method||'COD', ps=x.payment_status||method;
   const cls=ps==='Paid'?'pay-paid':ps==='Rejected'?'pay-rejected':ps==='Payment Pending'?'pay-pending':'pay-cod';
   return `<b>${esc(method)}</b><br><span class="pay-status ${cls}">${esc(ps)}</span>${method==='Easypaisa'?`<br><small>Account: Muhammad Mudassir</small><br><small>Number: 03499345762</small><br><span class="txid">TXID: ${esc(x.transaction_id||'Not provided')}</span><div class="payment-actions"><button class="smallbtn" onclick="setPayment(${x.id},'Paid')">✓ Mark Paid</button><button class="smallbtn danger" onclick="setPayment(${x.id},'Rejected')">Reject</button></div>`:''}`;
 };
 const rows=o.map(x=>`<tr><td><b>ND-${x.id}</b><br><small>${new Date(x.created_at).toLocaleString()}</small></td><td>${esc(x.customer_name)}<br><small>${esc(x.customer_email||'No email')}</small><br><small>${esc(x.phone)}</small></td><td>${esc(x.city||'')} ${x.province?`• ${esc(x.province)}`:''}<br><small>${esc(x.address)}</small></td><td>Rs. ${money(x.total)}<br><small>Delivery: ${x.delivery_fee?`Rs. ${money(x.delivery_fee)}`:'FREE'}</small></td><td>${paymentCell(x)}</td><td><select onchange="setStatus(${x.id},this.value)">${statuses.map(s=>`<option ${s===x.status?'selected':''}>${s}</option>`).join('')}</select>${x.tracking_no?`<br><small>NOVA: ${esc(x.tracking_no)}</small>`:''}${x.courier_tracking_no?`<br><small>${esc(x.courier)}: ${esc(x.courier_tracking_no)}</small>`:''}${x.tracking_url?`<br><small><a href="${esc(x.tracking_url)}" target="_blank">Tracking URL</a></small>`:''}</td><td><button class="smallbtn" onclick="showItems(${x.id})">Items</button><button class="smallbtn" onclick="addTracking(${x.id})">Tracking</button><button class="smallbtn" onclick="createShipment(${x.id})">Create Shipment</button></td></tr>`).join('');
 $('#orderList').innerHTML=`<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Delivery Address</th><th>Total</th><th>Payment</th><th>Status</th><th>Action</th></tr></thead><tbody>${rows}</tbody></table>`;
 $('#latestOrders').innerHTML=`<table class="table"><thead><tr><th>Order</th><th>Customer</th><th>Total</th><th>Payment</th><th>Status</th></tr></thead><tbody>${o.slice(0,6).map(x=>`<tr><td>ND-${x.id}</td><td>${esc(x.customer_name)}</td><td>Rs. ${money(x.total)}</td><td>${esc(x.payment_method||'COD')}<br><small>${esc(x.payment_status||'COD')}</small></td><td><span class="status">${x.status}</span></td></tr>`).join('')}</tbody></table>`;
}
$('#productForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const r=await api('/api/admin/products',{method:'POST',body:fd});const d=await r.json();if(!r.ok)return toast(d.error||'Could not add product');e.target.reset();toast('Product added to storefront');await Promise.all([loadProducts(),loadStats()])};
async function deleteProduct(id){if(!confirm('Delete this product?'))return;const r=await api(`/api/admin/products/${id}`,{method:'DELETE'}),d=await r.json();if(!r.ok)return toast(d.error||'Delete failed');toast('Product deleted');loadProducts();loadStats()}
async function editProduct(id){const p=await fetch(`/api/products/${id}`).then(r=>r.json());const name=prompt('Product name',p.name);if(name===null)return;const price=prompt('Selling price',p.price);if(price===null)return;const compare=prompt('Old/compare price',p.compare_price||0);if(compare===null)return;const stock=prompt('Stock',p.stock);if(stock===null)return;const r=await api(`/api/admin/products/${id}`,{method:'PATCH',body:JSON.stringify({name,price:Number(price),compare_price:Number(compare),stock:Number(stock),category:p.category,description:p.description||'',image:p.image||''})});const d=await r.json();if(!r.ok)return toast(d.error||'Update failed');toast('Product updated');loadProducts()}
async function setStatus(id,status){const r=await api(`/api/admin/orders/${id}`,{method:'PATCH',body:JSON.stringify({status})});if(r.ok){toast(`Order ND-${id}: ${status}`);loadStats();loadOrders()}}
async function setPayment(id,payment_status){const label=payment_status==='Paid'?'mark this Easypaisa payment as PAID':'reject this payment';if(!confirm(`Are you sure you want to ${label}?`))return;const r=await api(`/api/admin/orders/${id}/payment`,{method:'PATCH',body:JSON.stringify({payment_status})});const d=await r.json();if(!r.ok)return toast(d.error||'Payment update failed');toast(`Order ND-${id}: ${payment_status}`);await loadOrders();}
async function showItems(id){const items=await api(`/api/admin/order-items/${id}`).then(r=>r.json());alert(`Order ND-${id}\n\n`+items.map(x=>`${x.name} × ${x.quantity} — Rs. ${money(x.price*x.quantity)}`).join('\n'))}
async function addTracking(id){const courier=prompt('Courier name (e.g. Leopards)');if(courier===null)return;const tracking_no=prompt('Tracking number / CN');if(tracking_no===null)return;const r=await api(`/api/admin/orders/${id}/tracking`,{method:'PATCH',body:JSON.stringify({courier,tracking_no})});if(r.ok){toast('Tracking saved');loadOrders()}}
async function createShipment(id){const r=await api(`/api/admin/orders/${id}/create-shipment`,{method:'POST'}),d=await r.json();toast(d.error||'Shipment created')}

function csvCell(v){const x=String(v??'').replace(/"/g,'""');return `"${x}"`}
function exportOrdersCsv(){
  if(!lastOrders.length)return toast('No orders to export');
  const headers=['Order ID','Date','Customer','Email','Phone','Address','City','Province','Subtotal','Delivery Fee','Total','Payment Method','Transaction ID','Payment Status','Order Status','Courier','NOVA Tracking ID','Courier Tracking','Tracking URL'];
  const rows=lastOrders.map(o=>[ `ND-${o.id}`,o.created_at,o.customer_name,o.customer_email||'',o.phone,o.address,o.city,o.province,o.subtotal,o.delivery_fee,o.total,o.payment_method||'COD',o.transaction_id||'',o.payment_status||'COD',o.status,o.courier,o.tracking_no,o.courier_tracking_no||'',o.tracking_url||'' ]);
  const csv=[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');
  const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`nova-orders-${new Date().toISOString().slice(0,10)}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);
}
$('#exportOrders').onclick=exportOrdersCsv;

$('#refreshOrders').onclick=()=>{loadOrders();loadStats();toast('Orders refreshed')};
$('#passwordForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const r=await api('/api/admin/change-password',{method:'POST',body:JSON.stringify({password:f.get('password')})});const d=await r.json();if(!r.ok)return toast(d.error||'Could not update password');e.target.reset();toast('Admin password updated')};
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
if(token)showDashboard();
