import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import Database from 'better-sqlite3';
import bcrypt from 'bcryptjs';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const root=path.join(__dirname,'../..');
const databaseDir=path.join(root,'database');
fs.mkdirSync(databaseDir,{recursive:true});
const db=new Database(path.join(databaseDir,'nova.sqlite'));
const email=process.env.ADMIN_EMAIL || 'mudassir239200@gmail.com';
const password=process.env.ADMIN_PASSWORD || 'Nova@12345';
db.exec('CREATE TABLE IF NOT EXISTS admins(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL)');
const hash=bcrypt.hashSync(password,12);
db.prepare(`INSERT INTO admins(email,password_hash) VALUES(?,?) ON CONFLICT(email) DO UPDATE SET password_hash=excluded.password_hash`).run(email,hash);
console.log('\nNOVA DIGITAL admin login reset successfully.');
console.log('Email: '+email);
console.log('Password: '+password);
console.log('Start the store with: npm start\n');
